### ISSUE TITLE
Local reference to photos isn't working in the preview

### ISSUE THREAD

**Issue by MosheBiton** [jhuix/vscode-markdown-preview-showdown#1]
Title.

I tried the following syntax: ![](path-to-local-image) and it didn't preview the photo. I tested my syntax and the link with other methods to make sure it works. 

Referencing to external path works great.

**Comment by jhuix** [comment]
> Title.
> 
> I tried the following syntax: ![](path-to-local-image) and it didn't preview the photo. I tested my syntax and the link with other methods to make sure it works.
> 
> Referencing to external path works great.

This feature has been implemented in a new version >= v1.3.0，you can download the [new version](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown) to try it out.
