### ISSUE TITLE
AsciiMath inline equation rendering issue

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#2]
With
````
```AsciiMath
y=f(x)
```
````
for *display math* and `` `@y=f(x)@` `` for *inline math*,
only *display math* is rendered properly in *vscode-markdown-preview-showdown*. See picture below:
![image](https://user-images.githubusercontent.com/18078043/95664246-36352180-0b46-11eb-90cc-13cc4eb9fde8.png)

**Comment by jhuix** [comment]
First of all, thank you for your feedback.
Inline math of AsciiMath and LaTeX cannot be rendered correctly in the current version of mdps, but they will be rendered properly in the next version of mdps.

**Comment by jhuix** [comment]
@sebi5361 Thanks for your feedback.
Inline math of AsciiMath and LaTeX can be rendered properly in the current version of mdps, but the delimiters of inline math is \~...\~ for asciimath and $$...$$ for latex that cannot be allowed in the \`...\` delimiters for code.

**Comment by sebi5361** [comment]
Thank you very much!
Good to know.
I guess there is no real standard for this and you had to make a clever choice, am I right?

**Comment by jhuix** [comment]
> Thank you very much!
> Good to know.
> I guess there is no real standard for this and you had to make a clever choice, am I right?

Yes, there is no standard for inline math in markdown syntax, so all kinds of markdown parsers are custom private syntax.

**Comment by sebi5361** [comment]
BTW: Really nice job!

**Comment by jhuix** [comment]
This issue has been enhanced by [the >= 1.3.3 version](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown), please try it.

Inline LaTex math syntax compatible with [KaTex default delimiters](https://katex.org/docs/autorender.html#api):  `$$...$$`  or `\[...\]`  or `\(...\)`.

Inline ascii math syntax is changed to `@@...@@` or `\~...\~`.
