### ISSUE TITLE
Issue with "a" being badly rendered in AsciiMath

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#3]
````MarkDown
~"a"~

~text(a)~

```AsciiMath
"a"
```
````
is rendered like this
![image](https://user-images.githubusercontent.com/18078043/95689513-9644ca00-0c11-11eb-8333-5138734ca2b3.png)

Maybe `"` are converted to curly ones prior to AsciiMath being parsed?

**Comment by jhuix** [comment]
Because the old js module vesion of AsciiMath to Latex is not compatible with the new syntax. I will update the a new version of the js module to solve the problem.

**Comment by sebi5361** [comment]
Thank you!
I appreciate that you are so responsive and that your project is maintained and improved!

**Comment by sebi5361** [comment]
> ... AsciiMath to Latex ... version of the js module ...

As I understand there is an intermediate state before rendering with some  _AsciiMath to Latex_ conversion.
Thus is there and easy way to offer a feature of exporting the document to a Latex file?

**Comment by jhuix** [comment]
This issue has been fixed by [the >= 1.3.3 version](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown), please try it.

**Comment by sebi5361** [comment]
![image](https://user-images.githubusercontent.com/18078043/95858747-d7e28b80-0d5d-11eb-9ae2-547a282bb747.png)
Inline equations are not rendered anymore...

**Comment by jhuix** [comment]
Inline math syntax is changed.
Inline LaTex math syntax compatible with [KaTex default delimiters](https://katex.org/docs/autorender.html#api):  `$$...$$`  or `\[...\]`  or `\(...\)`.
Inline ascii math syntax is changed to `@@...@@` or `\~...\~`.

**Comment by sebi5361** [comment]
![image](https://user-images.githubusercontent.com/18078043/95859542-0f9e0300-0d5f-11eb-93a9-29fa8490683c.png)
`"this is text"` works great in display equation!

**Comment by sebi5361** [comment]
> Inline math syntax is changed.
> Inline LaTex math syntax compatible with [KaTex default delimiters](https://katex.org/docs/autorender.html#api): `$$...$$` or `\[...\]` or `\(...\)`.
> Inline ascii math syntax is changed to `@@...@@` or `\~...\~`.

![image](https://user-images.githubusercontent.com/18078043/95859871-8fc46880-0d5f-11eb-9932-d9cfad4bdaae.png)
Indeed!
Works great!
Thank you

**Comment by jhuix** [comment]
> ![image](https://user-images.githubusercontent.com/18078043/95858747-d7e28b80-0d5d-11eb-9ae2-547a282bb747.png)
> Inline equations are not rendered anymore...

Please change inline math syntax `~...~` to `@@...@@` , because the char  `~` of asciimath is ambiguous. See the table about asciimath below：

Type | TeX alt | See |
-- | -- | -- |
-= | equiv | ≡ |
~= | cong | ≅ |
~~ | approx | ≈ |
prop | propto | ∝

**Comment by sebi5361** [comment]
Indeed. It works great with `@@` and all my equations are rendered properly now!

![image](https://user-images.githubusercontent.com/18078043/95860479-61935880-0d60-11eb-967d-3b372bb2cdf4.png)
`\~` doesn't seem to work.

**Comment by jhuix** [comment]
> Indeed. It works great with `@@` and all my equations are rendered properly now!
> 
> ![image](https://user-images.githubusercontent.com/18078043/95860479-61935880-0d60-11eb-967d-3b372bb2cdf4.png)
> `\~` doesn't seem to work.

`\~` is \\\\~

**Comment by sebi5361** [comment]
As `$$` is used for Latex **display** equation, `@@` is not really consistent for AsciiMath **inline** equations, don't you think?
In my opinion, `` `@cos x@` `` or `` `~cos x~` `` would be a better choice, as `` `code` `` is for **inline** code.

**Comment by sebi5361** [comment]
> `\~` is `\\~`

![image](https://user-images.githubusercontent.com/18078043/95861339-90f69500-0d61-11eb-8ff5-4bf4cb0751ed.png)
It seems that `\\~` triggers a display equation??

**Comment by jhuix** [comment]
> ![image](https://user-images.githubusercontent.com/18078043/95861339-90f69500-0d61-11eb-8ff5-4bf4cb0751ed.png)
> It seems that `\\~` triggers a display equation??

Yes, `@@...@@` is single inline math, `\~...\~` is  block inline math.

**Comment by sebi5361** [comment]
> `\~...\~` is block inline math.

OK, so similar to:
````
```AsciiMath
"display equation"
```
````

**Comment by sebi5361** [comment]
Wouldn't it be possible to configure the markers for inline and display equations in the settings so anyone could choose his/her favorite?
I like `@` and `@@` for example which makes it look like `$` and `$$`.

**Comment by jhuix** [comment]
> Wouldn't it be possible to configure the markers for inline and display equations in the settings so anyone could choose his/her favorite?
> I like `@` and `@@` for example which makes it look like `$` and `$$`.

I suggest that this issue can be discussed in the form of submitting new issue.

**Comment by sebi5361** [comment]
> I suggest that this issue can be discussed in the form of submitting new issue.

OK, I'll do that.

**Comment by sebi5361** [comment]
> > ... AsciiMath to Latex ... version of the js module ...
> 
> As I understand there is an intermediate state before rendering with some _AsciiMath to Latex_ conversion.
> Thus is there and easy way to offer a feature of exporting the document to a Latex file?

I also created a new issue regarding this question in order to close the current issue.
