### ISSUE TITLE
Bad rendering of empty-line-separated formulas in an AsciiMath block

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#5]
A neat feature while entering formulas is to be able to type them one after another is an AsciiMath block.
MarkdownPlus offers this possibility by parsing AsciiMath such a way when separating formulas by an empty line. See below:
![image](https://user-images.githubusercontent.com/18078043/95697012-a8d4f880-0c3d-11eb-93e5-ba7a61705ce4.png)
On *vscode-markdown-preview-showdown* all formulas are rendered stacked one after another in a single line. Blank lines are just ignored.

**Comment by jhuix** [comment]
I'll try to implement this feature that multiple ascii or latex math are separated by an empty line .

**Comment by jhuix** [comment]
This issue has been enhanced by [the >= 1.3.3 version](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown), please try it.

**Comment by sebi5361** [comment]
Works great!
![image](https://user-images.githubusercontent.com/18078043/95858942-26902580-0d5e-11eb-9b44-bf8b94382173.png)
Thank you!
