### ISSUE TITLE
AsciiMath matrices are not rendered

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#6]
````
```AsciiMath
[[a,b],[c,d]]
```
````
is not rendered.

**Comment by jhuix** [comment]
Because the old js module vesion of AsciiMath to Latex is not compatible with this syntax. I will update the a new version of the js module to solve the problem.

**Comment by jhuix** [comment]
This issue has been fixed by [the >= 1.3.3 version](https://marketplace.visualstudio.com/items?itemName=jhuix.markdown-preview-showdown), please try it.

**Comment by sebi5361** [comment]
![image](https://user-images.githubusercontent.com/18078043/95859267-9ef6e680-0d5e-11eb-816c-d0a3ce491e0c.png)
Works great!
Thank you
