### ISSUE TITLE
Switching between markdown flavors

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#7]
_vscode-markdown-preview-showdown_ doesn't render **line breaks** similarly to the embedded markdown viewer.
See below: 
![image](https://user-images.githubusercontent.com/18078043/95789163-4af7ed80-0cdd-11eb-9784-816006a948ea.png)
above picture left column | above picture center column | above picture right column
----------|---------|--------
markdown plain input | default markdown interpreter | _vscode-markdown-preview-showdown_ interpreter

I think we talk of differ _flavors_ (maybe it is not the appropriate term) for those parser language interpretation differences!?

I tried to play with the extension settings adding adding, for example, `"markdown-preview-showdown.flavor": "vanilla"` in the `settings.json` file, as mentioned in the [documentation](https://github.com/jhuix/vscode-markdown-preview-showdown#extension-settings), but unfortunately it didn't change anything.

Could you explain how to change the markdown _flavor_ (if I am using the appropriate term)?

**Comment by jhuix** [comment]
Default flavor is "github", it can be rendered correctly with the **line breaks** that be inputted by enter key.
How do you enter text?

**Comment by sebi5361** [comment]
I am entering text pressing the `enter` key...

**Comment by sebi5361** [comment]
Yes "github" flavor works as expected with your viewer.
I think the default markdown viewer works with the "original" flavor that displays text one after another if not separated by `space + space + line break`.
How to switch your viewer to this flavor?

**Comment by jhuix** [comment]
> Yes "github" flavor works as expected with your viewer.
> I think the default markdown viewer works with the "original" flavor that displays text one after another if not separated by `space + space + line break`.
> How to switch your viewer to this flavor?

OK. I will open showdown's native flavors include ["github", "ghost", "vanilla", "original"] in the next version

**Comment by jhuix** [comment]
> > Yes "github" flavor works as expected with your viewer.
> > I think the default markdown viewer works with the "original" flavor that displays text one after another if not separated by `space + space + line break`.
> > How to switch your viewer to this flavor?
> 
> OK. I will open showdown's native flavors include ["github", "ghost", "vanilla", "original"] in the next version

OR,  try to set "markdown-preview-showdown.flavor": "original" in settings.json file for version 1.3.3.

**Comment by sebi5361** [comment]
Adding `"markdown-preview-showdown.flavor": "original"` to `%APPDATA%\Code\User\settings.json` definitely triggered a modification to the rendering, as I had to close and reopen the display panel to see the rendered markdown correctly again.
However still it looks like the "github" flavor...

**Comment by jhuix** [comment]
> Adding `"markdown-preview-showdown.flavor": "original"` to `%APPDATA%\Code\User\settings.json` definitely triggered a modification to the rendering, as I had to close and reopen the display panel to see the rendered markdown correctly again.
> However still it looks like the "github" flavor...

Try the new version 1.3.4 again. The new version adds the flavor and delimiters setting.

**Comment by sebi5361** [comment]
The `flavor` settings works perfectly. Neat!
Thank you
