### ISSUE TITLE
Configure the markers for inline and display equations in the settings

### ISSUE THREAD

**Issue by sebi5361** [jhuix/vscode-markdown-preview-showdown#8]
>> Wouldn't it be possible to configure the markers for inline and display equations in the settings so anyone could choose his/her favorite?
>> I like `@` and `@@` for example which makes it look like `$` and `$$`.

> I suggest that this issue can be discussed in the form of submitting new issue.

> Try the new version 1.3.4 again. The new version adds the flavor and delimiters setting.

Regarding delimiter settings, I have tried those:
`{"left": "$$", "right": "$$", "display": true },{"left": "@", "right": "@", "asciimath": true}`
leading to:
![image](https://user-images.githubusercontent.com/18078043/96074268-8a266a00-0ea8-11eb-929c-83474cb0736a.png)
According to this rendering, my interpretation is that `$$` triggers Latex display equations, and `@` triggers AsciiMath inline equations.
Shouldn't there be 4 delimiter sets (`left` and `right`) to configure?

- `latex_inline`
- `latex_display`
- `asciimath_inline`
- `asciimath_display`

I am not that clear  with  the current settings: For example I didn't figure out yet how to trigger Latex inline equations, neither AsciiMath  display equations as
````
```AsciiMath

```
````
seem to  be deactivated (which is not a bad thing).

Additionally, it might improve the user's experience to have the Katex delimiter box prefiled with the default settings, so he/she can tweak them on demand, with a possibility to set them back to their default values.

What do you think of my remarks and observations of the current possibilities?

Thanks so much for your reactivity and progression!

**Comment by sebi5361** [comment]
> Try the new version 1.3.4 again. The new version adds the flavor and delimiters setting.

Regarding delimiter settings, I have tried those:
`{"left": "$$", "right": "$$", "display": true },{"left": "@", "right": "@", "asciimath": true}`
leading to:
![image](https://user-images.githubusercontent.com/18078043/96074268-8a266a00-0ea8-11eb-929c-83474cb0736a.png)
According to this rendering, my interpretation is that `$$` triggers Latex display equations, and `@` triggers AsciiMath inline equations.
Shouldn't there be 4 delimiter sets (`left` and `right`) to configure?

- `latex_inline`
- `latex_display`
- `asciimath_inline`
- `asciimath_display`

I am not that clear  with  the current settings: For example I didn't figure out yet how to trigger Latex inline equations, neither AsciiMath  display equations as
````
```AsciiMath

```
````
seem to  be deactivated.

Additionally, it might improve the user's experience to have the Katex delimiter box prefiled with the default settings, so he/she can tweak them on demand, with a possibility to set them back to their default values.

What do you think of my remarks and observations of the current possibilities?

Thanks so much for your reactivity and progression!

**Comment by jhuix** [comment]
Language code block syntax as

    ```[language name]
    ```
that be based on code block syntax as

    ```
    ```
is specified by GitHub. When you choose "original" flavor,  the default value of "ghCodeBlocks" option is false inside showdown, this means that code block syntax of github-style is turned off. So in the case of "orginal" flavor,  AsciiMath display equations as

    ```[AsciiMath]
    ```

is deactivated. Do you want to turn on "ghCodeBlocks" option in the case of "original" flavor ?

**Comment by jhuix** [comment]
I will split the katexDelimiter into 4 delimiter(left and right) :

- texmathInlineDelimiter
- texmathDisplayDelimiter
- asciimathInlineDelimiter
- asciimathDisplayDelimiter

and update the default settings to empty character, this means that set them back to default values of katex delimiter .

**Comment by sebi5361** [comment]
> Do you want to turn on "ghCodeBlocks" option in the case of "original" flavor ?

Not necessarily... I just didn't know. Thanks for telling me!
I can always use the GitHub flavor or set my Katex delimiters correctly to trigger display equations.

However, in a general manner, I think, the most parameters that can be tweaked in the `settings.json` file, the better it is. No need for fancy GUI setting menus for advanced configuration though... Other people might disagree.

**Comment by jhuix** [comment]
Try the new version 1.3.6 again.  The 4 math delimiters setting are used and the name of all settings are adjusted in the new version.

**Comment by sebi5361** [comment]
Indeed it seems to work as intended, with some limitations though.

A small glitch however:
Maybe the "Add Item" button in settings could be removed as there is no real reason for it to be there. See button below:
![image](https://user-images.githubusercontent.com/18078043/96440219-f3d7a880-1207-11eb-8c1c-0272db3194e5.png)

On a larger consideration level:
My opinion is that there is almost a consensus today that Latex equations should use `$`-`$` delimiter pairs, respectively `$$`-`$$`, for inline, respectively display, equations. But from what I have experienced with the current software version this is not possible today as nesting `$`  signs cannot be done.

**I think this limitation is dommageable and that having this feature is really an important aspect if you want to gain acceptance among users for your viewer...**

From a more selfish point of view (regarding my specific use case):
Improving the software to allow nesting delimiters would allow me to set `@`-`@`, respectively `@@`-`@@`, delimiters for inline, respectively display, AsciiMath equations. From what I have observed out there those are the delimiters used in many AsciiMath-enabled editors such as Markdown Plus, noteroot Editor and others...

**Comment by jhuix** [comment]
> A small glitch however:
> Maybe the "Add Item" button in settings could be removed as there is no real reason for it to be there

The "Add Item" button in settings cann't be removed, because it is the object configuration of vscode, and also to expand the attribute easily in the future

**Comment by jhuix** [comment]
> On a larger consideration level:
> My opinion is that there is almost a consensus today that Latex equations should use `$`-`$` delimiter pairs, respectively `$$`-`$$`, for inline, respectively display, equations. But from what I have experienced with the current software version this is not possible today as nesting `$` signs cannot be done.
> 
> **I think this limitation is dommageable and that having this feature is really an important aspect if you want to gain acceptance among users for your viewer...**
> 
> From a more selfish point of view (regarding my specific use case):
> Improving the software to allow nesting delimiters would allow me to set `@`-`@`, respectively `@@`-`@@`, delimiters for inline, respectively display, AsciiMath equations. From what I have observed out there those are the delimiters used in many AsciiMath-enabled editors such as Markdown Plus, noteroot Editor and others...

The '$' character is meaningful in latexmath, and the '@' character is also meaningful in asciimath. So 
the mdps extension does not default select the '$', '@' characters , but allows users to set the two single characters using the 4  delimiters configuration. And I'll use your suggestions in the next version to adjust the default values of inline and display settings for asciimath to inline is '\\\~...\\\~' or '\\@...\\@', display is '@@...@@'.

**Comment by sebi5361** [comment]
> And I'll use your suggestions in the next version to adjust the default values of inline and display settings for asciimath to inline is '\\\~...\\\~' or '\\@...\\@', display is '@@...@@'.

Markdown Plus and noteroot Editor use `@...@`, not `\@...\@`. Having the same delimiters would be neat!

**Comment by jhuix** [comment]
> > And I'll use your suggestions in the next version to adjust the default values of inline and display settings for asciimath to inline is '\~...\~' or '\@...\@', display is '@@...@@'.
> 
> Markdown Plus and noteroot Editor use `@...@`, not `\@...\@`. Having the same delimiters would be neat!

Because RegEx `@.` syntax has been defined in the syntax specified by github style, `@ ` ... ` @` will be used as the default setting of ascii inline math. Note: `@ ` =  `@` char + ` `space char, ` @` = ` `space char + `@` char

**Comment by sebi5361** [comment]
> Because RegEx `@.` syntax has been defined in the syntax specified by github style...

Can you tell me what `@.` has been defined for?
`@.` doesn't seem to be parsed at all by MDPS, leaving room for `@`...`@` delimiters... Having no extra spaces would be a must indeed!
`~`...`~` works though.

Why can't I set asciiDisplay to `@@\r\n`...`\r\n@@`?
